# Generated by Django 4.1.7 on 2023-03-07 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=255, null=True, verbose_name='Slug')),
                ('named_url', models.CharField(blank=True, max_length=255, verbose_name='Named URL')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menu',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item name')),
                ('named_url', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Named URL')),
                ('lft', models.PositiveIntegerField(default=0, help_text='*Do not fill. Will be calculated automatically.', verbose_name='Left key*')),
                ('rht', models.PositiveIntegerField(default=0, help_text='*Do not fill. Will be calculated automatically.', verbose_name='Right key*')),
                ('level', models.PositiveIntegerField(default=0, help_text='*Do not fill. Will be calculated automatically.', verbose_name='Nesting level*')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='menu.menu', verbose_name='Menu item')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='menu.menuitem', verbose_name='Parent item')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
                'ordering': ('level', 'lft', 'id'),
            },
        ),
    ]
